### PR TITLE
Upgrade to isort 5.7.0

### PR DESCRIPTION
**Pull request by akainth015**
For context, see the [original pull request](https://github.com/facebookresearch/vissl/pull/187).

### CODE REVIEW

**Comment by prigoyal** [comment]
@uhbuhb , Can we update the MLHFellowship/vissl master to be in sync with the master of `facebookresearch/vissl` ? I believe a recent PR landed in VISSL which made a few related changes and hence we will need to rebase @akainth015's PR to ensure no merge conflicts + keeping the relevant changes only.

**Comment by uhbuhb** [comment]
> @uhbuhb , Can we update the MLHFellowship/vissl master to be in sync with the master of `facebookresearch/vissl` ? I believe a recent PR landed in VISSL which made a few related changes and hence we will need to rebase @akainth015's PR to ensure no merge conflicts + keeping the relevant changes only.

done.

**Comment by prigoyal** [comment]
thank you @uhbuhb 

@akainth015 , can you rebase this PR to latest master and update? we should be able to merge your PR soon afterwards :)

**Comment by akainth015** [comment]
Wow, I thought GitHub collapsed the rebased commits once `master` was updated, I guess not.

**Comment by uhbuhb** [comment]
this is a comment to try to trigger circleCI?

**Comment by akainth015** [comment]
Tests passing. GPU tests say that GPU is not provisioned in CI

**Comment by uhbuhb** [comment]
aha! so circle is working.. I had to disable the gpu tests because they dont give gpu resources for the "free" tier but yes, looks like the cpu tests passed :)

**Review by prigoyal — APPROVED** [review]
Looks amazing!! thank you @akainth015 and @grace-omotoso !

Super cool work and very grateful to have you guys :)

**Pull request merged**
